### ISSUE TITLE
Improve player mute/unmute system

### ISSUE THREAD

**Issue by Chenterito** [diamante0018/DisablePlutoChat#39]
Currently, I realized that the "mute" command works based on "clientid", that is, if I mute "Juan" who has the clientid "5", and then another player "Pedro" connects and gets the clientid" 5", this player will also be muted.
A list could be implemented where the GUID of the players is stored so that there are no such problems. Wherever you go comparing the guids within the list, and even better if the plugin itself creates a file and stores the muted guids so they persist across server restarts.

**Comment by diamante0018** [comment]
Feel free to sponsor the project knowing that it took me 30 minutes to code the stuff you requested 😄 
https://github.com/diamante0018/diamante0018

Keep in mind that is project is dead so if you wanted me to make a release with your requests I would like a symbolic donation.
I think it's pretty reasonable to ask.

**Comment by Chenterito** [comment]
Thank you very much, I hope my donation helps. Although I also hope to implement that the plugin stores in a file the guids to persist the restarts of the server.
Another request, possibility to port this plugin to BO2 Plutonium.
[Donation](https://www.imagenes-temporales.com/subidas/ver/w0r34g/)

**Comment by diamante0018** [comment]
Yes it does implement the store.
You may find a release here, https://github.com/diamante0018/DisablePlutoChat/releases/tag/v1.0.1.
I have tested this locally, you can load the DLL as a server plugin.

**Comment by diamante0018** [comment]
The file with guid is saved in admin folder found in the game folder

**Comment by Chenterito** [comment]
When trying to load the plugin, the server starts to reboot constantly. I think there is some error.
